language: python

services:
  - docker
  - mysql

branches:
  only:
  - master
  
env:
  - SPONGE_DB_URI=mysql://root:@localhost/sponge

before_script:
  - mysql -u root --password="" < TestCases/travis_sponge.sql

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover TestCases
  - make travis
