language: python

services:
  - docker
  - mysql

branches:
  only:
  - master

before_script:
  - mysql -u root --password="" < REST-API/TestCases/travis_sponge.sql

install:
  - pip install -r REST-API/requirements.txt

script:
  - python -m unittest discover REST-API/TestCases
  - make travis
