openapi: 3.0.0
info:
  description: This is the swagger file that goes with our server code for the sponge
    REST-API
  version: 1.0.0
  title: SPONGE REST-API documentation
paths:
  /dataset:
    get:
      operationId: dataset.read
      tags:
        - Dataset
      summary: Read one dataset
      description: Read one dataset
      parameters:
        - name: disease_name
          in: query
          description: name of the disease to get
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successfully read dataset from dataset data operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  dataset_ID:
                    type: integer
                    description: Id of the dataset
                  disease_name:
                    type: string
                    description: Name of the diseae
                  data_origin:
                    type: string
                    description: Dataset origin (database name, etc.)
                  disease_type:
                    type: string
                    description: Type of the disease
                  download_url:
                    type: string
                    description: URL to dataset annotation
            application/xml:
              schema:
                type: object
                properties:
                  dataset_ID:
                    type: integer
                    description: Id of the dataset
                  disease_name:
                    type: string
                    description: Name of the diseae
                  data_origin:
                    type: string
                    description: Dataset origin (database name, etc.)
                  disease_type:
                    type: string
                    description: Type of the disease
                  download_url:
                    type: string
                    description: URL to dataset annotation
                xml:
                  name: dataset
  /ceRNANetwork/ceRNAInteraction:
    get:
      operationId: geneInteraction.read_all_to_one_gene
      tags:
        - GeneInteraction
      summary: Read all ceRNANetwork interactions the gene of interest in the dataset of interest is involed in
      description: Read one dataset
      parameters:
        - name: disease_name
          in: query
          description: name of the disease to get
          required: false
          schema:
            type: string
        - name: ensg_number
          in: query
          description: ensg number of the gene of interest(e.g. ENSG00000259090) (this or gene_symbol is needed to get results)
          required: false
          schema:
            type: string
        - name: gene_symbol
          in: query
          description: gene symbol of the gene of interest(e.g. SEPT7P1) (this or ensg_number is needed to get results)
          required: false
          schema:
            type: string
        - name: pValue
          in: query
          required: false
          description: cutoff of the pValue
          schema:
            type: number
        - name: pValueDirection
          in: query
          required: false
          description: direction (<, > or =) in which the pValue cutoff should go
          schema:
            type: string
            enum:
              - <
              - ">"
            default: <
        - name: mscore
          in: query
          required: false
          description: cutoff of the mscore
          schema:
            type: number
        - name: mscoreDirection
          in: query
          required: false
          description: direction (<, > or =) in which the mscore cutoff should go
          schema:
            type: string
            enum:
              - <
              - ">"
            default: <
        - name: correlation
          in: query
          required: false
          description: cutoff of the correlation
          schema:
            type: number
        - name: correlationDirection
          in: query
          required: false
          description: direction (<, > or =) in which the correlation cutoff should go
          schema:
            type: string
            enum:
              - <
              - ">"
            default: <
        - name: information
          in: query
          description: defines if each gene should contain all available information or not (if False just ensg_nr will be shown)
          required: false
          schema:
            type: boolean
            default: true
      responses:
        "200":
          description: Read all ceRNA interactions where gene of interesest in
            the searched disease (if provided) is involved in
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    interactions_genegene_ID:
                      type: integer
                      description: internal database ID as primary key
                    run_ID:
                      type: integer
                      description: internal database ID for different runs with SPONGE in
                        the same expression values for one disease
                    gene_ID1:
                      type: string
                      description: one of the two interacting ceRNA
                    gene_ID2:
                      type: string
                      description: the other part of the ceRNA interaction
                    p_value:
                      type: number
                      description: adjusted pValue of the ceRNA interaction
                    mscore:
                      type: number
                      description: mscore of the ceRNA interaction
                    correlation:
                      type: number
                      description: correlation of the ceRNA interaction
            application/xml:
              schema:
                type: array
                items:
                  properties:
                    interactions_genegene_ID:
                      type: integer
                      description: internal database ID as primary key
                    run_ID:
                      type: integer
                      description: internal database ID for different runs with SPONGE in
                        the same expression values for one disease
                    gene_ID1:
                      type: string
                      description: one of the two interacting ceRNA
                    gene_ID2:
                      type: string
                      description: the other part of the ceRNA interaction
                    p_value:
                      type: number
                      description: adjusted pValue of the ceRNA interaction
                    mscore:
                      type: number
                      description: mscore of the ceRNA interaction
                    correlation:
                      type: number
                      description: correlation of the ceRNA interaction   
  /ceRNANetwork/miRNAInteraction:
    get:
      operationId: geneInteraction.read_all_to_one_mirna
      tags:
        - GeneInteraction
      summary: Read all ceRNANetwork interactions the where the miRNA of interest contribute to
      description: Read all ceRNANetwork interactions the where the miRNA of interest contribute to
      parameters:
        - name: disease_name
          in: query
          description: name of the disease to get
          required: false
          schema:
            type: string
        - name: mimat_number
          in: query
          description: name of the miRNA of interest
          required: true
          schema:
            type: string
        - name: information
          in: query
          description: long or short information variant for mirna?
          required: false
          schema:
            type: boolean
            default: true
      responses:
        "200":
          description: Read all ceRNA interactions where miRNA of interesest in
            the searched disease (if provided) contributes to
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    interacting_miRNAs_ID:
                      type: integer
                      description: internal database ID as primary key
                    interactions_genegene:
                      type: string
                      description: ceRNA interaction the miRNA contributes to
                    mirna:
                      type: string
                      description: information about the miRNA of interest
            application/xml:
              schema:
                type: array
                items:
                  properties:
                    interacting_miRNAs_ID:
                      type: integer
                      description: internal database ID as primary key
                    interactions_genegene:
                      type: string
                      description: ceRNA interaction the miRNA contributes to
                    mirna:
                      type: string
                      description: information about the miRNA of interest
servers:
  - url: /sponge